"""Simplified options market-making engine."""

from __future__ import annotations

from dataclasses import dataclass, replace

from analytics.greeks import Greeks, GreeksEngine
from models.black_scholes import BlackScholesModel
from utils.instruments import EuropeanOption
from utils.market import MarketEnvironment
from utils.validation import require_non_negative, require_positive


@dataclass(frozen=True)
class MarketMakingConfig:
    """Configuration for option quoting and inventory risk controls."""

    base_spread: float = 0.10
    min_spread: float = 0.01
    inventory_limit: float = 100.0
    base_quote_size: float = 10.0
    inventory_spread_sensitivity: float = 0.50
    inventory_skew_sensitivity: float = 0.35
    gamma_spread_sensitivity: float = 1.00
    vega_spread_sensitivity: float = 0.002
    adverse_selection_buffer: float = 0.00

    def __post_init__(self) -> None:
        """Validate market-making controls."""
        require_non_negative(self.base_spread, "base_spread")
        require_non_negative(self.min_spread, "min_spread")
        require_positive(self.inventory_limit, "inventory_limit")
        require_positive(self.base_quote_size, "base_quote_size")
        require_non_negative(self.inventory_spread_sensitivity, "inventory_spread_sensitivity")
        require_non_negative(self.inventory_skew_sensitivity, "inventory_skew_sensitivity")
        require_non_negative(self.gamma_spread_sensitivity, "gamma_spread_sensitivity")
        require_non_negative(self.vega_spread_sensitivity, "vega_spread_sensitivity")
        require_non_negative(self.adverse_selection_buffer, "adverse_selection_buffer")


@dataclass(frozen=True)
class InventoryState:
    """Current option inventory and cash generated by market-making trades."""

    option_position: float = 0.0
    cash: float = 0.0


@dataclass(frozen=True)
class OptionQuote:
    """Bid/ask quote and associated risk diagnostics."""

    fair_value: float
    bid: float
    ask: float
    mid: float
    spread: float
    quote_size: float
    inventory_skew: float
    gamma_exposure: float
    vega_exposure: float
    theta_decay: float
    inventory_ratio: float


@dataclass(frozen=True)
class MarketMakingEngine:
    """Quote European options with inventory- and Greeks-aware adjustments."""

    option: EuropeanOption
    market: MarketEnvironment
    config: MarketMakingConfig = MarketMakingConfig()

    def fair_value(self) -> float:
        """Return Black-Scholes fair value."""
        return BlackScholesModel(option=self.option, market=self.market).price()

    def greeks(self) -> Greeks:
        """Return Black-Scholes Greeks used for risk-aware quoting."""
        model = BlackScholesModel(option=self.option, market=self.market)
        return GreeksEngine(model=model).all()

    def quote(self, inventory: InventoryState | None = None) -> OptionQuote:
        """Return bid/ask quote adjusted for inventory and option risk."""
        state = inventory or InventoryState()
        fair_value = self.fair_value()
        greeks = self.greeks()
        inventory_ratio = self._inventory_ratio(state.option_position)
        gamma_exposure = state.option_position * greeks.gamma
        vega_exposure = state.option_position * greeks.vega
        theta_decay = state.option_position * greeks.theta

        spread = self._spread(
            inventory_ratio=inventory_ratio,
            gamma_exposure=gamma_exposure,
            vega_exposure=vega_exposure,
        )
        inventory_skew = -self.config.inventory_skew_sensitivity * inventory_ratio * spread
        mid = fair_value + inventory_skew
        bid = max(mid - 0.5 * spread, 0.0)
        ask = max(mid + 0.5 * spread, bid + self.config.min_spread)

        return OptionQuote(
            fair_value=fair_value,
            bid=bid,
            ask=ask,
            mid=mid,
            spread=ask - bid,
            quote_size=self._quote_size(inventory_ratio),
            inventory_skew=inventory_skew,
            gamma_exposure=gamma_exposure,
            vega_exposure=vega_exposure,
            theta_decay=theta_decay,
            inventory_ratio=inventory_ratio,
        )

    def execute_trade(
        self,
        inventory: InventoryState,
        side: str,
        quantity: float,
        quote: OptionQuote | None = None,
    ) -> InventoryState:
        """Update inventory after a customer trades against the market maker.

        Args:
            inventory: Current inventory state.
            side: ``"buy"`` if the market maker buys option inventory at bid,
                ``"sell"`` if the market maker sells option inventory at ask.
            quantity: Option quantity traded.
            quote: Optional precomputed quote.

        Returns:
            Updated inventory state.
        """
        require_positive(quantity, "quantity")
        active_quote = quote or self.quote(inventory)

        if side == "buy":
            return replace(
                inventory,
                option_position=inventory.option_position + quantity,
                cash=inventory.cash - quantity * active_quote.bid,
            )
        if side == "sell":
            return replace(
                inventory,
                option_position=inventory.option_position - quantity,
                cash=inventory.cash + quantity * active_quote.ask,
            )

        raise ValueError("side must be either 'buy' or 'sell'.")

    def inventory_warning(self, inventory: InventoryState) -> bool:
        """Return True when inventory is at or beyond the configured limit."""
        return abs(inventory.option_position) >= self.config.inventory_limit

    def _spread(
        self,
        inventory_ratio: float,
        gamma_exposure: float,
        vega_exposure: float,
    ) -> float:
        """Return risk-adjusted quote spread."""
        spread = max(self.config.base_spread, self.config.min_spread)
        spread *= 1.0 + self.config.inventory_spread_sensitivity * abs(inventory_ratio)
        spread += self.config.gamma_spread_sensitivity * abs(gamma_exposure)
        spread += self.config.vega_spread_sensitivity * abs(vega_exposure)
        spread += self.config.adverse_selection_buffer
        return max(spread, self.config.min_spread)

    def _quote_size(self, inventory_ratio: float) -> float:
        """Return quoted size reduced as inventory approaches limits."""
        size_multiplier = max(0.10, 1.0 - abs(inventory_ratio))
        return self.config.base_quote_size * size_multiplier

    def _inventory_ratio(self, option_position: float) -> float:
        """Return inventory as a clipped fraction of configured inventory limit."""
        raw_ratio = option_position / self.config.inventory_limit
        return max(min(raw_ratio, 1.0), -1.0)

