"""Gym-compatible trading environment for reinforcement learning agents."""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Any

import numpy as np
import pandas as pd

try:
    import gymnasium as gym
    from gymnasium import spaces
except ImportError:  # pragma: no cover - exercised only in incomplete environments
    gym = None
    spaces = None


class TradingAction(IntEnum):
    """Discrete action space used by the first trading agents."""

    SELL = 0
    HOLD = 1
    BUY = 2


@dataclass(frozen=True)
class TradingEnvironmentConfig:
    """Configuration shared by Gym-compatible trading environments."""

    initial_cash: float = 100_000.0
    transaction_cost_bps: float = 1.0
    max_position: float = 1.0
    reward_window: int = 20
    lookback_window: int = 20
    reward_scale: float = 100.0
    risk_aversion: float = 0.0
    allow_short: bool = True


class TradingEnvironment(gym.Env if gym is not None else object):
    """Single-asset Buy/Sell/Hold environment with risk-adjusted rewards.

    The observation is a flattened lookback window of normalized OHLCV bars plus the
    current position. Actions are discrete: sell, hold, buy. Transaction costs are
    charged whenever the target exposure changes.
    """

    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        prices: pd.DataFrame,
        config: TradingEnvironmentConfig | None = None,
    ) -> None:
        if gym is None or spaces is None:
            raise ImportError(
                "Install gymnasium to use TradingEnvironment: python -m pip install gymnasium"
            )

        self.config = config or TradingEnvironmentConfig()
        self.prices = _validate_prices(prices)
        if len(self.prices) <= self.config.lookback_window + 1:
            raise ValueError("price data must exceed lookback_window by at least two rows")

        self.close = self.prices["close"].to_numpy(dtype=np.float64)
        self.current_step = self.config.lookback_window
        self.position = 0.0
        self.equity = self.config.initial_cash
        self.returns: list[float] = []
        self.equity_curve: list[float] = []

        self.action_space = spaces.Discrete(3)
        observation_size = self.config.lookback_window * 5 + 1
        self.observation_space = spaces.Box(
            low=-10.0,
            high=10.0,
            shape=(observation_size,),
            dtype=np.float32,
        )

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the environment to the first tradable timestamp."""

        del options
        if seed is not None:
            super().reset(seed=seed)

        self.current_step = self.config.lookback_window
        self.position = 0.0
        self.equity = self.config.initial_cash
        self.returns = []
        self.equity_curve = [self.equity]
        return self._observation(), self._info(0.0, 0.0, 0.0)

    def step(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Execute one trading action and advance to the next timestamp."""

        if self.current_step >= len(self.prices) - 1:
            return self._observation(), 0.0, True, False, self._info(0.0, 0.0, 0.0)

        target_position = self._target_position(TradingAction(int(action)))
        turnover = abs(target_position - self.position)
        transaction_cost = turnover * self.config.transaction_cost_bps / 10_000.0
        next_return = self.close[self.current_step + 1] / self.close[self.current_step] - 1.0
        portfolio_return = target_position * next_return - transaction_cost

        self.position = target_position
        self.equity *= 1.0 + portfolio_return
        self.returns.append(float(portfolio_return))
        self.equity_curve.append(float(self.equity))
        reward = self._reward(float(portfolio_return))
        self.current_step += 1

        terminated = self.current_step >= len(self.prices) - 1
        info = self._info(
            portfolio_return=float(portfolio_return),
            transaction_cost=float(transaction_cost),
            market_return=float(next_return),
        )
        return self._observation(), reward, terminated, False, info

    def render(self) -> None:
        """Print the current portfolio state."""

        print(
            f"step={self.current_step} equity={self.equity:.2f} "
            f"position={self.position:.2f}"
        )

    def strategy_returns(self) -> pd.Series:
        """Return timestamp-aligned portfolio returns generated by the environment."""

        start = self.config.lookback_window + 1
        index = self.prices.index[start : start + len(self.returns)]
        return pd.Series(self.returns, index=index, name="rl_strategy_return")

    def _target_position(self, action: TradingAction) -> float:
        """Map an action to the next target exposure."""

        if action is TradingAction.HOLD:
            return self.position
        if action is TradingAction.BUY:
            return self.config.max_position
        if self.config.allow_short:
            return -self.config.max_position
        return 0.0

    def _reward(self, portfolio_return: float) -> float:
        """Compute a Sharpe-like reward with optional risk penalty."""

        scaled_return = portfolio_return * self.config.reward_scale
        if len(self.returns) < max(2, self.config.reward_window):
            return float(scaled_return)

        recent = np.asarray(self.returns[-self.config.reward_window :], dtype=np.float64)
        rolling_volatility = float(recent.std(ddof=1))
        sharpe_like = float(recent.mean() / (rolling_volatility + 1e-12))
        risk_penalty = self.config.risk_aversion * rolling_volatility * self.config.reward_scale
        return sharpe_like - risk_penalty

    def _observation(self) -> np.ndarray:
        """Create normalized OHLCV state from the current lookback window."""

        start = self.current_step - self.config.lookback_window
        window = self.prices.iloc[start : self.current_step]
        close_anchor = float(window["close"].iloc[-1])
        price_state = window.loc[:, ["open", "high", "low", "close"]] / close_anchor - 1.0

        volume = window["volume"].astype(float)
        volume_std = float(volume.std(ddof=0))
        if volume_std == 0.0:
            volume_state = pd.Series(0.0, index=window.index)
        else:
            volume_state = (volume - volume.mean()) / volume_std

        state = pd.concat([price_state, volume_state.rename("volume")], axis=1)
        flattened = state.to_numpy(dtype=np.float32).reshape(-1)
        observation = np.append(flattened, np.float32(self.position)).astype(np.float32)
        return np.clip(observation, -10.0, 10.0).astype(np.float32)

    def _info(
        self,
        portfolio_return: float,
        transaction_cost: float,
        market_return: float,
    ) -> dict[str, Any]:
        """Return diagnostic information for evaluation and debugging."""

        return {
            "step": self.current_step,
            "equity": self.equity,
            "position": self.position,
            "portfolio_return": portfolio_return,
            "transaction_cost": transaction_cost,
            "market_return": market_return,
        }


def _validate_prices(prices: pd.DataFrame) -> pd.DataFrame:
    """Validate and normalize environment input data."""

    required = ["open", "high", "low", "close", "volume"]
    missing = [column for column in required if column not in prices.columns]
    if missing:
        raise ValueError(f"missing required price columns: {missing}")
    if len(prices) < 3:
        raise ValueError("at least three price rows are required")

    clean = prices.loc[:, required].copy().dropna()
    if clean.empty:
        raise ValueError("price data is empty after dropping missing values")
    return clean.sort_index()
